version: '3'

services:

  blockstore:
    container_name: edx.${OPENEDX_PROJECT_NAME:-devstack}.blockstore
    image: opencraft/blockstore:latest
    build:
      context: .
      dockerfile: Dockerfile-3.8
    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash"]
    networks:
      default:
      devstack:
        aliases:
          - edx.devstack.blockstore
    ports:
      - "18250:18250"
    volumes:
      - ./:/blockstore/app/:cached
      # Increment when all users will need a new venv, like after a Python version update.
      - blockstore_venv_3_8_5:/blockstore/venv/
    environment:
      - MYSQL_DATABASE=blockstore_db
      - MYSQL_USER=root
      - MYSQL_HOST=mysql57
      - MYSQL_PORT=3306

networks:
  devstack:
    external:
      name: ${OPENEDX_PROJECT_NAME:-devstack}_default

volumes:
  blockstore_venv_3_8_5:
