version: 2.1

workflows:
  version: 2.1
  validate:
    jobs:
      - tests:
          matrix:
            parameters:
              python_version: ["3.8"]
      - quality
jobs:
  tests:
    parameters:
      python_version:
        type: string
        default: "3.8"
    working_directory: /blockstore/app/
    docker:
      - image: python:<< parameters.python_version >>-alpine
      - image: mysql:5.6
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
        environment:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    environment:
      MYSQL_DATABASE: "blockstore_db"
      MYSQL_USER: "root"
      MYSQL_HOST: "127.0.0.1"
      MYSQL_PORT: 3306

    steps:

      - checkout

      - run:
          name: Install requirements
          command: |
            apk update && apk upgrade
            apk add bash bash-completion build-base git perl mariadb-dev libffi-dev
            python<< parameters.python_version >> -m venv /blockstore/venv
            source /blockstore/venv/bin/activate
            make requirements

      - run:
          name: Run tests
          command: |
            source /blockstore/venv/bin/activate
            make test

  quality:

    working_directory: /blockstore/app/

    docker:
      - image: python:3.5-alpine

    steps:

      - checkout

      - run:
          name: Install requirements
          command: |
            apk update && apk upgrade
            apk add bash bash-completion build-base git perl mariadb-dev libffi-dev
            python3.5 -m venv /blockstore/venv
            source /blockstore/venv/bin/activate
            make requirements

      - run:
          name: Run quality
          command: |
            source /blockstore/venv/bin/activate
            make quality
